### ISSUE TITLE
Fraudulent transaction on woo commerce

### ISSUE THREAD

**Issue by JessicaSOS** [lastmjs/javascript-practice#170]
has already been postponed to May 2018 and has been corrected. However, now it is not corrected anymore. 

Many people try to make fraudulent transactions on our website with stolen credit cards. Transactions are automatically "failed" (failed). See the number of red attempts on the failed order attachment. However, even if the transaction was not successful, an invoice is created and the trade in item is entered in the inventory as "sold" and the quantity goes from 1 to 0. This is a problem each time we have fraud. As you can see, we have them regularly. We have to go into each item manually correct it in addition to removing an invoice that should not exist.
<img width="941" alt="invoice from fraudulent transaction" src="https://user-images.githubusercontent.com/40500094/49173225-178e5e80-f311-11e8-9c86-424b640ba5d0.png">
<img width="938" alt="customer richard byers" src="https://user-images.githubusercontent.com/40500094/49173276-3987e100-f311-11e8-9e2c-4a4d8e324845.png">
<img width="944" alt="10103" src="https://user-images.githubusercontent.com/40500094/49173352-7a7ff580-f311-11e8-8f7d-d76ebf1c7727.png">
<img width="938" alt="order from woo commerce" src="https://user-images.githubusercontent.com/40500094/49173525-f67a3d80-f311-11e8-8b72-12a53bd86ddc.png">

--
French:
a déjà été reporter en mai 2018 et a été corrigé. Cependant, maintenant ce n'est plus corrigé. J'aimerais aussi ajouter qu'une facture se crée dès qu'une transation est effectué, qu'elle soit frauduleuse ou pas.

Beaucoup de gens essaient de faire des transactions frauduleuses sur notre site internet avec des cartes de crédits volés. Les transactions sont donc automatiquement "échouées" (échoué). Voir le nombre de tentatives en rouge sur la pièce jointe "failed order". Cependant, même si la transaction n'a pas réussi, l'item est inscrit dans l'inventaire comme "sold" et la quantité passe de 1 à 0. Cela pose problème à chaque fois que nous avons des fraudes. Comme vous pouvez voir, nous en avons régulièrement. Nous devons aller dans chaque item le corriger manuellement.

**Comment by lastmjs** [comment]
I don't think this is the repository you're looking for :)

**Comment by JessicaSOS** [comment]
This problem still exists. Why this issue was put as closed? Please reopen and correct.

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Jordan Last <notifications@github.com> 
Envoyé : 28 novembre 2018 19:16
À : lastmjs/javascript-practice <javascript-practice@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Author <author@noreply.github.com>
Objet : Re: [lastmjs/javascript-practice] Fraudulent transaction on woo commerce (#170)

 

I don't think this is the repository you're looking for :)

**Comment by lastmjs** [comment]
This project and repository doesn't have anything to do with Woo commerce, I'm not sure what you're talking about. I believe you have the wrong repository, this repo is for javascriptpractice.com
